[package]
name = "stars"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true
keywords.workspace = true


[dependencies]
rand.workspace = true
bevy.workspace = true

relativity.workspace = true
